### ISSUE TITLE
cryze process not found

### ISSUE THREAD

**Issue by legouju** [xerootg/cryze_v2#17]
Getting the same issue like: https://github.com/xerootg/cryze_v2/issues/14#issue-2548864989
Unfortunately, I am unable to connect to the android container with scrcpy unless I am doing something wrong.

My OS is a headless install of Debian GNU/Linux 12 (Openmediavualt)
Frigate and wyze-bridge works fine with my existing wyze v1 camera/other cameras

docker-compose yaml file:
```
networks:
  cryze_network:
    driver: bridge

services:
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    env_file: # shared credentials with cryze_api
      - /docker/data/Frigate/Frigate.env
    networks:
      - cryze_network
    ports:
      - 8884:5000 # WEB-UI          
      - 8885:1935 # RTMP
      - 8886:8554 # RTSP
      - 8887:8888 # HLS
      - 8889:8889 #WebRTC
      - 8890:8189/udp # WebRTC/ICE
    environment:
      - ENABLE_AUDIO=True
      - AUDIO_CODEC=AAC
      - ON_DEMAND=False
      - LLHLS=True
      - WB_AUTH=False # Set to false to disable web and stream auth.
      - 
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri:/dev/dr
    networks:
      - cryze_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/frigate/data/config:/config
      - /srv/dev-disk-by-uuid-c5a97f91-d77b-45ae-97e8-d033e67fe246/frigate/media:/media/frigate
    ports:
      - 8971:8971
      - 8553:5000 # Internal unauthenticated access. Expose carefully.
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
      - 1984:1984 # go2rtc ui
      - 1935:1935 # go2rtc incoming rtmp stream
    environment:
      - FRIGATE_RTSP_PASSWORD="password"

  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    network_mode: service:cryze_android_app
    privileged: true # this may not be necessary for all setups.
  
  cryze_android_app:
    restart: unless-stopped
    networks:
      - cryze_network
    build:
      context: ./cryze_android_app
      dockerfile: Dockerfile
      args:
        CRYZE_RTSP_SERVER: "localhost"
        CRYZE_BACKEND_URL: "http://cryze_api:8799" 
    privileged: true
    ports:
      - 5555:5555
    command:
      - androidboot.use_memfd=1
      - androidboot.redroid_net_ndns=1
      - androidboot.redroid_net_dns1=127.0.0.11
      - androidboot.redroid_gpu_mode=host
      - androidboot.redroid_gpu_node=/dev/dri/renderD128
  cryze_api:
    ## volume mount /data
    ## make sure .env is updated
    restart: unless-stopped
    volumes:
      - cryze_api_cryze_data:/data
    networks:
      - cryze_network
    build:
      context: ./cryze_api
      dockerfile: Dockerfile
    ports:
      - 8799:8080
    env_file:
      - /docker/data/Frigate/Frigate.env

volumes:
  cryze_api_cryze_data:
```
